export const NOT_SUPPORTED = "NOT_SUPPORTED";
export const ACCESS_DENIED = "ACCESS_DENIED";
export const INVALID_CLAIM = "INVALID_CLAIM";
export const INVALID_JWT = "INVALID_JWT";
export const MISSING_JWT = "MISSING_JWT";
