CREATE TABLE IF NOT EXISTS logs (
	log TEXT NOT NULL UNIQUE,
  created_at INTEGER NOT NULL,
  tags TEXT NOT NULL,
  PRIMARY KEY (log)
);

CREATE TABLE IF NOT EXISTS entries (
  id INTEGER,
  commit_id TEXT NOT NULL UNIQUE,
	log TEXT NOT NULL,
  data TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  PRIMARY KEY (id)
);